version: '3'

tasks:
  # Builds the go-dj binary
  build:
    cmds:
      - task: lint
      - go build -v -o go-dj .
      - chmod +x go-dj

  # Installs dependencies necessary for go-dj to output audio
  install_deps:
    cmds:
       - sudo apt install libasound2-dev libudev-dev pkg-config
       - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3

  # Runs go-dj
  run:
    cmds:
      - task: build
      - ./go-dj s

  # Lints go-dj
  lint:
    cmds:
      - golangci-lint run ./...

  # Run the tests
  test:
    cmds:
      - go test -v ./content -run Test